# Generated by Django 2.1.1 on 2018-09-12 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_auto_20180912_0638'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='first_enrollable_paid_seat_sku',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
