# Generated by Django 2.1.1 on 2018-09-12 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_auto_20180912_0644'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='number',
            field=models.CharField(blank=True, default='', max_length=25),
        ),
    ]
