# Generated by Django 2.1.1 on 2018-09-12 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='has_enrollable_seats',
            field=models.NullBooleanField(),
        ),
        migrations.AlterField(
            model_name='course',
            name='key',
            field=models.CharField(blank=True, max_length=60, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='mobile_available',
            field=models.NullBooleanField(),
        ),
        migrations.AlterField(
            model_name='course',
            name='published',
            field=models.NullBooleanField(),
        ),
    ]
