# Generated by Django 2.1.1 on 2018-09-12 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_auto_20180912_0646'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='organization',
            field=models.CharField(blank=True, default='', max_length=35),
        ),
    ]
